[build]
  base = "."
  install = "npm ci"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NPM_CONFIG_OPTIONAL = "true"
  NPM_CONFIG_IGNORE_SCRIPTS = "false"